locale: "en-US"
site_theme: "mint"
title: "Cong Lin"
title_separator: "|"
name: &name "Cong Lin"
description: &description "Academic homepage of Dr Cong Lin"
url: "https://lc1286068435.github.io"
baseurl: ""
repository: "lc1286068435/lc1286068435.github.io"

# Public professional profile only
author:
  avatar: ""
  name: "Cong Lin"
  bio: "Research Assistant Professor working on functional solids for catalysis, energy and separation."
  location: "Hong Kong SAR"
  employer: "Department of Chemistry, The Hong Kong Polytechnic University"
  uri: "https://www.polyu.edu.hk/chem/people/academic-staff/dr-lin-cong/"
  email: "cong.lin@polyu.edu.hk"
  googlescholar: "https://scholar.google.com/citations?user=KuQDVfAAAAAJ&hl=zh-CN"
  orcid: "https://orcid.org/0000-0003-0021-5055"
  researchgate: "https://www.researchgate.net/profile/Cong-Lin-3"
  github: "lc1286068435"

publication_category:
  manuscripts:
    title: "Selected Publications"

teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider: false
atom_feed:
  hide: false
analytics:
  provider: false
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile
  - gulpfile.js
  - node_modules
  - package.json*
  - Rakefile
  - tmp
  - vendor
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
permalink: /:categories/:title/
timezone: Asia/Hong_Kong
compress_html:
  clippings: all
  ignore:
    envs: development
